const TABS_SNAP = 'TABS_SNAPSHOT'
const TABS_SETSNAP = 'TABS_SETSNAPSHOT'
const TABS_REMOVETAB = 'TABS_REMOVETAB'
const TABS_REMOVEWINDOW = 'TABS_REMOVEWINDOW'

export {
  TABS_SNAP,
  TABS_SETSNAP,
  TABS_REMOVETAB,
  TABS_REMOVEWINDOW
}