const TABS_SNAP = 'TABS_SNAPSHOT'
const TABS_SETSNAP = 'TABS_SETSNAPSHOT'
const TABS_REMOVETAB = 'TABS_REMOVETAB'
const TABS_REMOVEWINDOW = 'TABS_REMOVEWINDOW'
const TABS_SETRECIPENAME = 'TABS_SETRECIPENAME'
const TABS_SETRECIPETAG = 'TABS_SETRECIPETAG'
const TABS_ADDRECIPETAG = 'TABS_ADDRECIPETAG'
const TABS_REMOVERECIPETAG = 'TABS_REMOVERECIPETAG'
const TABS_SETRECIPEPUBLIC = 'TABS_SETRECIPEPUBLIC'
const TABS_CLEARFIELDS = 'TABS_CLEARFIELDS'
const TABS_CREATERECIPE = 'TABS_CREATERECIPE'
const TABS_CREATERECIPE_SUCCESS = 'TABS_CREATERECIPE_SUCCESS'
const TABS_CREATERECIPE_PENDING = 'TABS_CREATERECIPE_PENDING'
const TABS_CREATERECIPE_FAILED = 'TABS_CREATERECIPE_FAILED'

const SEARCH_SETSEARCHTERMS = 'SEARCH_SETSEARCHTERMS'
const SEARCH_SETDROPDOWNOPEN = 'SEARCH_SETDROPDOWNOPEN'
const SEARCH_SETSORTBY = 'SEARCH_SETSORTBY'
const SEARCH_PREVIOUSROW = 'SEARCH_PREVIOUSROW'
const SEARCH_NEXTROW = 'SEARCH_NEXTROW'
const SEARCH_SETROW = 'SEARCH_SETROW'

const AUTH_LOGIN = 'AUTH_LOGIN'
const AUTH_LOGOUT = 'AUTH_LOGOUT'
const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING'
const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED'
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'

const POPUP_TOGGLE_CREATEVISIBLE = 'POPUP_TOGGLE_CREATEVISIBLE'
const POPUP_TOGGLE_DETAILVISIBLE = 'POPUP_TOGGLE_DETAILVISIBLE'
const POPUP_SELECTROW = 'POPUP_SELECTROW'

export {
  TABS_SNAP,
  TABS_SETSNAP,
  TABS_REMOVETAB,
  TABS_REMOVEWINDOW,
  TABS_SETRECIPENAME,
  TABS_SETRECIPETAG,
  TABS_ADDRECIPETAG,
  TABS_REMOVERECIPETAG,
  TABS_SETRECIPEPUBLIC,
  TABS_CLEARFIELDS,
  SEARCH_SETDROPDOWNOPEN,
  SEARCH_SETSEARCHTERMS,
  SEARCH_SETSORTBY,
  SEARCH_NEXTROW,
  SEARCH_PREVIOUSROW,
  SEARCH_SETROW,
  AUTH_LOGIN,
  AUTH_LOGOUT,
  AUTH_LOGIN_PENDING,
  AUTH_LOGIN_FAILED,
  AUTH_LOGIN_SUCCESS,
  TABS_CREATERECIPE,
  TABS_CREATERECIPE_PENDING,
  TABS_CREATERECIPE_SUCCESS,
  TABS_CREATERECIPE_FAILED,
  POPUP_TOGGLE_CREATEVISIBLE,
  POPUP_TOGGLE_DETAILVISIBLE,
  POPUP_SELECTROW
}