export const POPUP = {
  OPEN_DASHBOARD: 'OPEN_DASHBOARD',
  OPEN_DASHBOARD_SUCCESS: 'OPEN_DASHBOARD_SUCCESS'
}

export const TIMER = {
  START: 'TIMER_START',
  STOP: 'TIMER_STOP',
  TICK: 'TIMER_TICK',
  START_INTERVAL: 'START_INTERVAL',
  START_INTERVAL_SUCCESS: 'START_INTERVAL_SUCCESS',
  STOP_TIMER_SUCCESS: 'STOP_TIMER_SUCCESS'
}

export const BLACKLIST = {
  SET: 'SET_BLACKLIST',
  START: 'START_BLACKLIST_BLOCKING',
  BLOCKED: 'BLACKLIST_SITE_BLOCKED',
  STOP: 'STOP_BLACKLIST_BLOCKING'
}

export const SESSION = {
  
}